import { Inter } from 'next/font/google'
import Link from "next/link"
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav style={{
          wdth: '100 %',
          display: 'flex',
          justifyContent: 'center',
          alignItems: 'center',
          backgroundColor: 'teal',
          fontSize: '40px',
          textTransform: "capitalize",
          padding: "20px 0",
        }}>
          <Link style={{marginRight:"7px",}} href="/">Home</Link>
          <Link style={{marginRight:"7px",}} href="/posts">Posts</Link>
          <Link style={{marginRight:"7px",}} href="/articles">Articles</Link>
        </nav>
        {children}
      </body>
    </html>
  )
}
